# PLAN: GitHub Actions workflow to run pre-commit across Python versions
name: Lint

on:
  push:
    paths:
      - '**/*.py'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'dev-requirements.txt'
  pull_request:
    paths:
      - '**/*.py'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'dev-requirements.txt'

jobs:
  precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'dev-requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
